[workspace]
members = [".", "migration"]

[package]
name = "belajar-rust-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
axum = "0.8.8"
axum-extra = "0.12.5"
axum-test = "18.7.0"
chrono = { version = "0.4.44", features = ["serde"] }
dotenvy = "0.15.7"
http = "1.4.0"
sea-orm = { version = "1.1.19", features = ["sqlx-mysql", "runtime-tokio-rustls", "macros", "with-chrono"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
tower = "0.5.3"
